<?php

namespace Tests\Feature;

use App\Models\Product;
use App\Models\User;
use App\Notifications\ImportantUpdateProduct;
use App\Retail\StockResponse;
use Database\Seeders\RetailWithProductSeeder;
use Facades\App\Retail\RetailFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

class TrackCommandTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(RetailWithProductSeeder::class);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_track_product_stock()
    {
        $product = Product::first();

        $this->assertFalse($product->inStock());

        $this->mockRetailRequest();

        $this->artisan('stock:track')->expectsOutput('Done');

        $this->assertTrue($product->inStock());
    }
}
